// ---------- Sistema de Habilidades por CÓDIGO ----------
// Monstros armazenam somente o código (ex.: H001). O nome é apenas apresentação.
// Assim, alterar o nome de uma habilidade não quebra os dados dos monstros.
const HABILIDADE_NOMES = {
  H001: "Kaiju", H002: "Get Over Here", H003: "Chove Chuva Chove sem Parar",
  H004: "Mais que Nada", H005: "Rei dos Ringues", H006: "Sangue de um Deus",
  H007: "Donquexote", H008: "Cegueira", H009: "No Fire", H010: "Sentinela Noturna",
  H011: "Predator", H012: "Dragão Celestial", H013: "Domínio das Águas", H014: "9 Vidas",
  H015: "Fúria Colossal", H016: "Noite Lunar", H017: "Reino Glacial", H018: "Olhos de Fogo",
  H019: "Galope Maldito", H020: "Aposta Brutal", H021: "Encanto das Águas",
  H022: "StarPlatinum", H023: "Matrix", H024: "Deus Da Guerra", H025: "Brecha",
  H026: "Invencível", H027: "Contra ataque", H028: "BattleForm", H029: "Boto Rosa",
  H030: "The World", H031: "Made in Heaven", H032: "King Crimson", H033: "Crazy Diamond", H034: "Golden Experience", H035: "One For All", H036: "All For One", H037: "Gear Fifth", H038: "Haki do Rei", H039: "Bankai", H040: "Getsuga Tenshou", H041: "Sharingan", H042: "Mangekyō", H043: "Modo Sábio", H044: "Instinto Superior", H045: "Kaioken", H046: "Super Saiyajin", H047: "Rinnegan", H048: "Hadouken", H049: "Shoryuken", H050: "Fatality", H051: "Flawless Victory", H052: "Varia Suit", H053: "Master Sword", H054: "Triforce", H055: "Power of Friendship", H056: "Plot Armor", H057: "Respawn", H058: "Checkpoint", H059: "New Game+", H060: "Lag Spike", H061: "Critical Hit", H062: "Save Point", H063: "Konami Code", H064: "Portal Gun", H065: "Nanomachines, Son!", H066: "I Am Iron Man", H067: "Wakanda Forever", H068: "Snyder Cut", H069: "Speed Force", H070: "Mighty Morphin", H071: "It's Morphin Time!",
  H072: "Firmeza", H073: "Agilidade", H074: "Concentração", H075: "Força Bruta", H076: "Casca Dura", H077: "Resistência", H078: "Foco", H079: "Regeneração", H080: "Drenagem", H081: "Vigor", H082: "Instinto", H083: "Precaução", H084: "Persistência", H085: "Fôlego", H086: "Equilíbrio", H087: "Olho Vivo", H088: "Impulso", H089: "Impacto", H090: "Calma", H091: "Retaliação", H092: "Barreira", H093: "Sorte", H094: "Atenção", H095: "Passos Leves", H096: "Pele Seca", H097: "Absorção", H098: "Faísca", H099: "Calor", H100: "Frieza", H101: "Coragem", H102: "Vontade", H103: "Pressa", H104: "Armadura", H105: "Apoio", H106: "Caçador", H107: "Renovação", H108: "Reserva", H109: "Sintonia", H110: "Reflexo", H111: "Fortuna", H112: "Troca Equivalente",
};
const HABILIDADE_CODIGOS = Object.fromEntries(Object.entries(HABILIDADE_NOMES).map(([c,n])=>[n,c]));

const HABILIDADES = {
  H001: { aoEntrar(proprio, oponente, batalha) { const dano=Math.max(1,Math.floor(oponente.status.hpMax*.1)); oponente.hpAtual=Math.max(0,oponente.hpAtual-dano); batalha.log.push(`${proprio.nome} provoca um pequeno terremoto! ${oponente.nome} perde ${dano} de HP.`); } },
  H002: { temPrioridade(proprio, alvo, golpe, efetividade) { return efetividade > 1; } },
  H003: { aoEntrar(proprio, oponente, batalha) { proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.5); batalha.chuva=true; batalha.log.push(`${proprio.nome} traz a chuva! Velocidade aumentada.`); } },
  H004: { aoEntrar(proprio,oponente,batalha){ batalha.florido=true; if(proprio.nome==='Sabic'){ if(!proprio._maisQueNadaBuff){ proprio.status.ataque=Math.floor(proprio.status.ataque*1.35); proprio.status.ataqueEspecial=Math.floor(proprio.status.ataqueEspecial*1.35); proprio._maisQueNadaBuff=true; } batalha.log.push(`${proprio.nome} invoca o Campo de Flores! Ataque e Ataque Especial aumentados em 35%.`); } else { batalha.log.push(`${proprio.nome} invoca o Campo de Flores!`); } } },
  H005: { chanceNocauteImediato:.05 },
  // Loflame: a habilidade aumenta a efetividade ofensiva, mas NÃO cria
  // nenhuma imunidade defensiva nem transforma tipos em 0x.
  H006: { somenteOfensiva:true, sobrescreverEfetividade(tipoGolpe, tiposAlvoTexto, padrao) { const superE=["Elétrico","Psíquico","Pedra","Dragão","Fantasma","Dark","Fada","Lutador","Inseto"]; const ts=tiposAlvoTexto.split('/').map(t=>t.trim()); if(ts.some(t=>superE.includes(t)))return Math.max(padrao,2); return null; } },
  H007: { aoEntrar(proprio, oponente, batalha) { if(estaImune(oponente,'intimidacao')){batalha.log.push(`${oponente.nome} ignorou a intimidação!`);return;} oponente.status.ataque=Math.floor(oponente.status.ataque*.65); batalha.log.push(`A presença de ${proprio.nome} intimida ${oponente.nome}! Ataque reduzido.`); } },
  H008: { aoAcertar(proprio, alvo, golpe, batalha) { if(estaImune(alvo,'cego'))return; if(Math.random()<.3){alvo.statusAlterado='cego'; batalha.log.push(`${alvo.nome} ficou Cego!`);} } },
  H009: { sobrescreverEfetividade(tipoGolpe, tiposAlvoTexto, padrao) { if(tipoGolpe==='Fogo'&&padrao>1)return 1; return null; } },
  H010: { aoEntrar(proprio, oponente, batalha) { proprio.status.defesa=Math.floor(proprio.status.defesa*1.5); batalha.log.push(`${proprio.nome} se prepara para a noite! Defesa aumentada.`); }, imunidades:['cego'] },
  H011: { aoDerrotarInimigo(proprio,batalha){ proprio.status.ataque=Math.floor(proprio.status.ataque*1.5); batalha.log.push(`${proprio.nome} fica ainda mais forte após a vitória!`); } },
  H012: { antesDoTurno(proprio,oponente,batalha){ if(!proprio._despertou&&proprio.hpAtual/proprio.status.hpMax<=.33){proprio.status.ataque=Math.floor(proprio.status.ataque*1.3); proprio.status.defesa=Math.floor(proprio.status.defesa*1.3); proprio._despertou=true; batalha.log.push(`${proprio.nome} desperta sua natureza dracônica!`);} }, aoDerrotarInimigo(proprio,batalha){proprio.status.ataque=Math.floor(proprio.status.ataque*1.35); batalha.log.push(`${proprio.nome} fica ainda mais forte após a vitória!`);} },
  H013: { sobrescreverEfetividade(tipoGolpe){ return tipoGolpe==='Água'?0:null; } },
  H014: { aoDesmaiar(proprio,batalha){proprio._vidasUsadas=proprio._vidasUsadas||0; if(proprio._vidasUsadas<9&&Math.random()<.5){proprio._vidasUsadas++;proprio.hpAtual=1;batalha.log.push(`${proprio.nome} sobrevive com 1 HP! (vida ${proprio._vidasUsadas}/9)`);return true;}return false;} },
  H015: { modificarAtaque(proprio){const perdido=1-proprio.hpAtual/proprio.status.hpMax;return Math.floor(proprio.status.ataque*(1+Math.min(1,perdido)));} },
  H016: { aoEntrar(proprio,oponente,batalha){batalha.campoNoturno=true;batalha.estrelado=true;batalha.log.push('A noite cai sobre o campo de batalha...');} },
  H017: { aoEntrar(proprio,oponente,batalha){batalha.log.push(`${proprio.nome} cobre o campo de neve...`);} },
  H018: { aoAcertar(proprio,alvo,golpe,batalha){if(golpe.tipo!=='Fogo'||estaImune(alvo,'queimado'))return;if(Math.random()<.3){alvo.statusAlterado='queimado';batalha.log.push(`${alvo.nome} foi Queimado!`);}} },
  H019: { modificarAtaque(proprio,alvo,golpe,agiuPrimeiro){if(agiuPrimeiro&&alvo.hpAtual/alvo.status.hpMax<.5)return Math.floor(proprio.status.ataque*1.3);return proprio.status.ataque;} },
  H020: { antesDoTurno(proprio,oponente,batalha){if(!proprio._estadoLunar&&proprio.hpAtual/proprio.status.hpMax<.25){proprio.status.ataque=Math.floor(proprio.status.ataque*2);proprio.status.defesa=Math.floor(proprio.status.defesa*.1);proprio._estadoLunar=true;batalha.log.push(`${proprio.nome} entra em Estado Lunar!`);}} },
  H021: { aoEntrar(proprio,oponente,batalha){if(estaImune(oponente,'confuso'))return;if(Math.random()<.3){oponente.statusAlterado='confuso';batalha.log.push(`${oponente.nome} ficou Confuso pelo canto de ${proprio.nome}!`);}} },

  // NOVAS
  H022: { aoEntrar(proprio){ if(!proprio._starPlatinum){proprio.status.ataque=Math.floor(proprio.status.ataque*1.13);proprio._starPlatinum=true;} } },
  H023: { nuncaErra:true },
  H024: { aoEntrar(proprio,oponente,batalha){ batalha.campoBatalha=true; const ch=['hpMax','ataque','defesa','ataqueEspecial','defesaEspecial','velocidade']; const s=ch[Math.floor(Math.random()*ch.length)]; if(s==='hpMax'){const antes=proprio.status.hpMax;proprio.status.hpMax=Math.floor(antes*1.1);proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+proprio.status.hpMax-antes);} else proprio.status[s]=Math.floor(proprio.status[s]*1.1); batalha.statusCampoBatalha=s; batalha.log.push(`${proprio.nome} invoca o Campo de Batalha! ${nomeStatus(s)} recebeu +10%.`); } },
  H025: { aoErroDoOponente(proprio,oponente,batalha){ const golpes=(proprio.golpesConhecidos||[]).filter(Boolean); if(!golpes.length)return; const g=buscarGolpeGlobal(golpes[Math.floor(Math.random()*golpes.length)]); if(!g||g.poder<=0)return; const ef=calcularEfetividadeGlobal(g,proprio,oponente); const r=calcularDanoGlobal(proprio,oponente,g,ef,batalha)*.5; const dano=Math.max(1,Math.floor(r)); oponente.hpAtual=Math.max(0,oponente.hpAtual-dano); batalha.log.push(`${proprio.nome} ativa Brecha e contra-ataca com ${g.nome}! (${dano} de dano)`); if(oponente.hpAtual<=0 && typeof tratarDesmaio==='function'){ const lado= batalha.timeJogador?.includes(oponente) ? 'jogador' : 'oponente'; tratarDesmaio(oponente,lado); } } },
  H026: { aoFimDoTurno(proprio,batalha){ if(proprio.hpAtual<=0)return; proprio._turnosInvencivel=(proprio._turnosInvencivel||0)+1; if(proprio._turnosInvencivel===6&&!proprio._invencivelAtivado){ for(const s of ['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade']) proprio.status[s]=Math.floor(proprio.status[s]*1.5); proprio.status.hpMax=Math.floor(proprio.status.hpMax*1.5); proprio.hpAtual=Math.min(proprio.status.hpMax,Math.floor(proprio.hpAtual*1.5)); proprio._invencivelAtivado=true; batalha.log.push(`${proprio.nome} permaneceu 5 turnos de pé e tornou-se INVENCÍVEL! +50% em todos os status.`); } } },
  H027: { aoTrocarEntrar(proprio,oponente,batalha){ const golpes=(proprio.golpesConhecidos||[]).filter(Boolean); if(!golpes.length)return; const g=buscarGolpeGlobal(golpes[Math.floor(Math.random()*golpes.length)]); if(!g||g.poder<=0)return; const ef=calcularEfetividadeGlobal(g,proprio,oponente); const dano=Math.max(1,Math.floor(calcularDanoGlobal(proprio,oponente,g,ef,batalha)*.5)); oponente.hpAtual=Math.max(0,oponente.hpAtual-dano); batalha.log.push(`${proprio.nome} entra com Contra ataque usando ${g.nome}! (${dano} de dano)`); if(oponente.hpAtual<=0 && typeof tratarDesmaio==='function'){ const lado= batalha.timeJogador?.includes(oponente) ? 'jogador' : 'oponente'; tratarDesmaio(oponente,lado); } } },
  H028: { aoDerrotarInimigo(proprio,batalha){ if(proprio._battleForm)return; proprio._battleForm=true; proprio.status.ataque=Math.floor(proprio.status.ataque*1.5); proprio.status.ataqueEspecial=Math.floor(proprio.status.ataqueEspecial*1.5); proprio.formaAnterior={nome:proprio.nome,tipo:proprio.tipo,png:proprio.png}; const rival=batalha._ultimoDerrotado; if(rival){proprio.nome=rival.nome;proprio.tipo=rival.tipo;proprio.png=rival.png;} batalha.log.push(`${proprio.formaAnterior.nome} assume uma nova BattleForm! +50% de Ataque e Ataque Especial.`); } },
  H029: { aoDerrotarInimigo(proprio,batalha){ const rival=batalha._ultimoDerrotado; if(!rival)return; proprio.nome=rival.nome; proprio.tipo=rival.tipo; proprio.png=rival.png; batalha.log.push(`${proprio.formaAnteriorNome||'O Boto'} copia ${rival.nome}: aparência e tipagem herdadas, mantendo seus próprios golpes!`); } },
  H030: { aoEntrar(proprio,oponente,batalha){ oponente.statusAlterado='paralisado'; oponente._duracaoStatus=1; batalha.log.push(`${proprio.nome} usa The World! ${oponente.nome} fica paralisado por 1 turno.`); } },
  H031: { aoEntrar(proprio,oponente,batalha){ proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.5); batalha._madeInHeaven=true; batalha.log.push(`${proprio.nome} acelera o tempo com Made in Heaven!`); } },
  H032: { ignorarDanoChance:.20 },
  H033: { antesDoTurno(proprio,oponente,batalha){ if(!proprio._crazyDiamondUsado&&proprio.hpAtual/proprio.status.hpMax<.5){ const cura=Math.floor(proprio.status.hpMax*.25); proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+cura); proprio._crazyDiamondUsado=true; batalha.log.push(`${proprio.nome} restaura ${cura} HP com Crazy Diamond!`); } } },
  H034: { aoFimDoTurno(proprio,batalha){ if(proprio.hpAtual>0){ const cura=Math.max(1,Math.floor(proprio.status.hpMax*.05)); proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+cura); } } },
  H035: { aoDerrotarInimigo(proprio,batalha){ proprio.status.ataque=Math.floor(proprio.status.ataque*1.2); batalha.log.push(`${proprio.nome} fortalece o One For All! Ataque +20%.`); } },
  H036: { aoDerrotarInimigo(proprio,batalha){ const rival=batalha._ultimoDerrotado; const stats=['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade']; const s=stats.find(k=>rival&&rival._bonusStats&&rival._bonusStats[k])||null; if(s){proprio.status[s]=Math.floor(proprio.status[s]*1.2); batalha.log.push(`${proprio.nome} rouba parte do ${nomeStatus(s)} com All For One!`);} } },
  H037: { antesDoTurno(proprio,oponente,batalha){ if(proprio.hpAtual/proprio.status.hpMax<.3&&!proprio._gearFifth){ for(const s of ['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade']) proprio.status[s]=Math.floor(proprio.status[s]*1.5); proprio._gearFifth=3; batalha.log.push(`${proprio.nome} desperta o Gear Fifth! +50% nos atributos por 3 turnos.`); } }, aoFimDoTurno(proprio){ if(proprio._gearFifth){proprio._gearFifth--; if(proprio._gearFifth===0){ for(const s of ['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade']) proprio.status[s]=Math.floor(proprio.status[s]/1.5); } } } },
  H038: { aoAcertar(proprio,alvo,golpe,batalha){ if(Math.random()<.2){alvo.statusAlterado='flinchar';alvo._duracaoStatus=1;batalha.log.push(`${alvo.nome} hesitou diante do Haki do Rei!`);} } },
  H039: { modificarPoder(proprio,golpe){ return proprio.hpAtual/proprio.status.hpMax<.5 ? Math.floor(golpe.poder*1.5) : golpe.poder; } },
  H040: { modificarPoderTipo(proprio,golpe){ return golpe.tipo==='Dark' ? 1.25 : 1; } },
  H041: { aoSerAtingido(proprio,atacante,golpe,batalha){ if(Math.random()<.25&&golpe&&golpe.codigo){ proprio._golpeCopiado=golpe.codigo; batalha.log.push(`${proprio.nome} copia ${golpe.nome||golpe.codigo} com Sharingan!`); } } },
  H042: { ignoraProtecao:true },
  H043: { aoEntrar(proprio,oponente,batalha){ proprio.status.ataqueEspecial=Math.floor(proprio.status.ataqueEspecial*1.25); proprio.status.defesaEspecial=Math.floor(proprio.status.defesaEspecial*1.25); batalha.log.push(`${proprio.nome} entra em Modo Sábio!`); } },
  H044: { esquivaChance:.25 },
  H045: { aoEntrar(proprio,oponente,batalha){ proprio.status.ataque=Math.floor(proprio.status.ataque*1.5); proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.5); batalha.log.push(`${proprio.nome} ativa Kaioken!`); }, aoFimDoTurno(proprio){ if(proprio.hpAtual>0){ proprio.hpAtual=Math.max(1,proprio.hpAtual-Math.max(1,Math.floor(proprio.status.hpMax*.05))); } } },
  H046: { antesDoTurno(proprio,oponente,batalha){ if(proprio.hpAtual/proprio.status.hpMax<.5&&!proprio._ssj){proprio.status.ataque=Math.floor(proprio.status.ataque*1.4);proprio._ssj=true;batalha.log.push(`${proprio.nome} desperta o Super Saiyajin!`);} } },
  H047: { aoSerAtingido(proprio,atacante,golpe,batalha){ if(Math.random()<.25&&golpe&&golpe.codigo){proprio._golpeCopiado=golpe.codigo;batalha.log.push(`${proprio.nome} usa o Rinnegan para copiar ${golpe.nome||golpe.codigo}!`);} } },
  H048: { modificarPoderTipo(proprio,golpe){ return golpe.tipo==='Lutador' ? 1.25 : 1; } },
  H049: { modificarPoder(proprio,golpe){ return golpe.prioridade>0 ? Math.floor(golpe.poder*1.3) : golpe.poder; } },
  H050: { aoAcertar(proprio,alvo,golpe,batalha){ if(alvo.hpAtual>0&&alvo.hpAtual/alvo.status.hpMax<=.10){alvo.hpAtual=0;batalha.log.push('FATALITY');batalha.log.push(`${proprio.nome} finalizou ${alvo.nome}!`);} } },
  H051: { aoFimDaBatalha(proprio,batalha){ if(proprio._hpInicial===proprio.hpAtual&&proprio.hpAtual>0){ for(const s of ['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade']) proprio.status[s]=Math.floor(proprio.status[s]*1.2); batalha.log.push(`${proprio.nome} conquistou uma FLAWLESS VICTORY!`); } } },
  H052: { multiplicadorDanoRecebido(tipo){ return ['Fogo','Gelo','Elétrico'].includes(tipo)?.7:1; } },
  H053: { modificarPoderTipo(proprio,golpe){ return proprio.hpAtual>=proprio.status.hpMax&&golpe.tipo==='Aço' ? 1.25 : 1; } },
  H054: { aoEntrar(proprio,oponente,batalha){ const s=['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade'][Math.floor(Math.random()*5)]; proprio.status[s]=Math.floor(proprio.status[s]*1.5); batalha.log.push(`${proprio.nome} recebe a bênção da Triforce: ${nomeStatus(s)} +50%.`); } },
  H055: { modificarDano(proprio,alvo,dano,batalha){ const aliados=(batalha.timeJogador||[]).includes(proprio)?batalha.timeJogador:(batalha.timeOponente||[]).includes(proprio)?batalha.timeOponente:[]; const vivos=Math.max(0,aliados.filter(x=>x&&x!==proprio&&x.hpAtual>0).length); return dano*(1+Math.min(.5,vivos*.1)); } },
  H056: { aoDesmaiar(proprio,batalha){ if(!proprio._plotArmorUsado&&Math.random()<.1){proprio._plotArmorUsado=true;proprio.hpAtual=1;batalha.log.push(`${proprio.nome} foi salvo pela PLOT ARMOR!`);return true;}return false;} },
  H057: { aoDesmaiar(proprio,batalha){ if(!proprio._respawnUsado){proprio._respawnUsado=true;proprio.hpAtual=Math.max(1,Math.floor(proprio.status.hpMax*.25));batalha.log.push(`${proprio.nome} deu RESPAWN!`);return true;}return false;} },
  H058: { antesDoTurno(proprio,oponente,batalha){ if(!proprio._checkpointUsado&&proprio.hpAtual/proprio.status.hpMax<.2){proprio._checkpointUsado=true;proprio.hpAtual=Math.max(proprio.hpAtual,Math.floor(proprio.status.hpMax*.4));batalha.log.push(`${proprio.nome} voltou ao CHECKPOINT!`);} } },
  H059: { aoDerrotarInimigo(proprio,batalha){ const s=['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade'][Math.floor(Math.random()*5)]; proprio.status[s]=Math.floor(proprio.status[s]*1.05); batalha.log.push(`${proprio.nome} ativou New Game+: ${nomeStatus(s)} +5%.`); } },
  H060: { aoAcertar(proprio,alvo,golpe,batalha){ if(Math.random()<.2){alvo.statusAlterado='flinchar';alvo._duracaoStatus=1;batalha.log.push(`${alvo.nome} sofreu um Lag Spike e perdeu o próximo turno!`);} } },
  H061: { bonusCritico:.15 },
  H062: { aoFimDaBatalha(proprio,batalha){ if(proprio.hpAtual>0){const cura=Math.max(1,Math.floor(proprio.status.hpMax*.1));proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+cura);} } },
  H063: { aoEntrar(proprio,oponente,batalha){ for(const s of ['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade']) proprio.status[s]=Math.floor(proprio.status[s]*1.3); proprio._konami=2;batalha.log.push(`${proprio.nome} ativou o KONAMI CODE! +30% por 2 turnos.`); }, aoFimDoTurno(proprio){ if(proprio._konami){proprio._konami--; if(proprio._konami===0){for(const s of ['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade']) proprio.status[s]=Math.floor(proprio.status[s]/1.3);}} } },
  H064: { aoSerAtingido(proprio,atacante,golpe,batalha){ if(Math.random()<.2&&atacante&&golpe&&golpe.poder>0){ const dano=Math.max(1,Math.floor(calcularDanoGlobal(proprio,atacante,golpe,1,batalha)*.75)); atacante.hpAtual=Math.max(0,atacante.hpAtual-dano); batalha.log.push(`${proprio.nome} usa Portal Gun e devolve ${dano} de dano!`); return true;} return false; } },
  H065: { antesDoTurno(proprio,oponente,batalha){ if(proprio.hpAtual/proprio.status.hpMax<.25&&!proprio._nano){proprio.status.defesa=Math.floor(proprio.status.defesa*1.75);proprio._nano=true;batalha.log.push(`${proprio.nome}: NANOMACHINES, SON! Defesa +75%.`);} } },
  H066: { aoEntrar(proprio,oponente,batalha){proprio.status.defesa=Math.floor(proprio.status.defesa*1.25);proprio.status.ataqueEspecial=Math.floor(proprio.status.ataqueEspecial*1.25);batalha.log.push(`${proprio.nome} ativa I Am Iron Man!`);} },
  H067: { aoAliadoDesmaiar(proprio,batalha){proprio._wakandaTurnos=3;proprio.status.defesa=Math.floor(proprio.status.defesa*1.5);batalha.log.push(`${proprio.nome}: WAKANDA FOREVER! Defesa +50% por 3 turnos.`);}, aoFimDoTurno(proprio){if(proprio._wakandaTurnos){proprio._wakandaTurnos--;if(proprio._wakandaTurnos===0)proprio.status.defesa=Math.floor(proprio.status.defesa/1.5);}} },
  H068: { reduzirDuracaoStatus:.5 },
  H069: { aoEntrar(proprio,oponente,batalha){proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.4);batalha.log.push(`${proprio.nome} canaliza a Speed Force!`);}, chanceDuplaAcao:.10 },
  H070: { aoEntrar(proprio,oponente,batalha){const s=['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade'][Math.floor(Math.random()*5)];proprio.status[s]=Math.floor(proprio.status[s]*1.3);batalha.log.push(`${proprio.nome}: MIGHTY MORPHIN! ${nomeStatus(s)} +30%.`);} },
  H071: { antesDoTurno(proprio,oponente,batalha){if(proprio.hpAtual/proprio.status.hpMax<.5&&!proprio._morphin){for(const s of ['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade'])proprio.status[s]=Math.floor(proprio.status[s]*1.2);proprio._morphin=true;batalha.log.push(`${proprio.nome}: IT'S MORPHIN TIME! +20% nos atributos.`);}} },
  H072: { aoEntrar(proprio,oponente,batalha){proprio.status.defesa=Math.floor(proprio.status.defesa*1.15);batalha.log.push(`${proprio.nome} ganhou Firmeza! Defesa +15%.`);} },
  H073: { aoEntrar(proprio,oponente,batalha){proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.15);batalha.log.push(`${proprio.nome} ganhou Agilidade! Velocidade +15%.`);} },
  H074: { aoEntrar(proprio,oponente,batalha){proprio.status.ataqueEspecial=Math.floor(proprio.status.ataqueEspecial*1.15);} },
  H075: { aoEntrar(proprio,oponente,batalha){proprio.status.ataque=Math.floor(proprio.status.ataque*1.15);} },
  H076: { multiplicadorDanoRecebido(tipo,golpe){return golpe?.categoria==='Físico'?.9:1;} },
  H077: { multiplicadorDanoRecebido(tipo,golpe,efetividade){return efetividade>1?.9:1;} },
  H078: { imunidades:['flinchar'] },
  H079: { aoFimDoTurno(proprio){if(proprio.hpAtual>0){const c=Math.max(1,Math.floor(proprio.status.hpMax*.03));proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+c);}} },
  H080: { aoAcertar(proprio,alvo,golpe,batalha){if(golpe?.poder>0){const c=Math.max(1,Math.floor((proprio._ultimoDanoCausado||0)*.05));if(c>0)proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+c);}} },
  H081: { antesDoTurno(proprio,oponente,batalha){if(!proprio._vigor&&proprio.hpAtual/proprio.status.hpMax<.5){proprio.status.defesa=Math.floor(proprio.status.defesa*1.2);proprio._vigor=true;}} },
  H082: { antesDoTurno(proprio){if(!proprio._instinto&&proprio.hpAtual/proprio.status.hpMax<.5){proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.15);proprio._instinto=true;}} },
  H083: { multiplicadorDanoRecebido(){return estadoBatalha?.turno===0?.8:1;} },
  H084: { antesDoTurno(proprio){if(!proprio._persistencia&&proprio.hpAtual/proprio.status.hpMax<.25){proprio.status.defesaEspecial=Math.floor(proprio.status.defesaEspecial*1.2);proprio._persistencia=true;}} },
  H085: { antesDoTurno(proprio){if(!proprio._folego&&proprio.hpAtual/proprio.status.hpMax<.5){proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+Math.max(1,Math.floor(proprio.status.hpMax*.05)));proprio._folego=true;}} },
  H086: { aoEntrar(proprio){const ss=['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade'];const menor=ss.reduce((a,b)=>proprio.status[a]<proprio.status[b]?a:b);const maior=ss.reduce((a,b)=>proprio.status[a]>proprio.status[b]?a:b);if(proprio.status[menor]<proprio.status[maior]*.7)proprio.status[menor]=Math.floor(proprio.status[menor]*1.15); } },
  H087: { bonusPrecisao:10 },
  H088: { aoAcertar(proprio){if(!proprio._impulso){proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.1);proprio._impulso=true;}} },
  H089: { aoAcertar(proprio,alvo,golpe){if(golpe?.categoria==='Físico'&&!proprio._impacto){proprio.status.ataque=Math.floor(proprio.status.ataque*1.1);proprio._impacto=true;}} },
  H090: { aoSerAtingido(proprio){if(!proprio._calma){proprio.status.defesaEspecial=Math.floor(proprio.status.defesaEspecial*1.1);proprio._calma=true;}} },
  H091: { aoSerAtingido(proprio){proprio._retaliacao=true;} },
  H092: { multiplicadorDanoRecebido(tipo,golpe,efetividade){if(!this._barreiraUsada){this._barreiraUsada=true;return .5;}return 1;} },
  H093: { esquivaChance:.10 },
  H094: { bonusPrecisao:10 },
  H095: { ignoraArmadilhas:true },
  H096: { aoSerAtingido(proprio,atacante,golpe){if(golpe?.tipo==='Água'){proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+Math.max(1,Math.floor(proprio.status.hpMax*.04)));}} },
  H097: { aoSerAtingido(proprio,atacante,golpe){if(golpe?.tipo==='Planta'){proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+Math.max(1,Math.floor(proprio.status.hpMax*.08)));}} },
  H098: { aoSerAtingido(proprio,atacante,golpe){if(golpe?.tipo==='Elétrico')proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.1);} },
  H099: { multiplicadorDanoRecebido(tipo){return tipo==='Fogo'?.8:1;} },
  H100: { multiplicadorDanoRecebido(tipo){return tipo==='Gelo'?.8:1;} },
  H101: { imunidades:['intimidacao'] },
  H102: { aoDesmaiar(proprio,batalha){if(!proprio._vontadeUsada){proprio._vontadeUsada=true;proprio.hpAtual=1;batalha.log.push(`${proprio.nome} resistiu com Vontade!`);return true;}return false;} },
  H103: { antesDoTurno(proprio){if(estadoBatalha?.turno===0)proprio.status.velocidade=Math.floor(proprio.status.velocidade*1.2);} },
  H104: { multiplicadorDanoRecebido(){return .9;} },
  H105: { antesDoTurno(proprio){if(proprio._apoio)return;const vivos=(estadoBatalha?.timeJogador?.includes(proprio)?estadoBatalha.timeJogador:estadoBatalha?.timeOponente||[]).filter(m=>m&&m!==proprio&&m.hpAtual>0).length;if(vivos>0){proprio.status.defesa=Math.floor(proprio.status.defesa*1.1);proprio._apoio=true;}} },
  H106: { modificarDano(proprio,alvo,dano){return alvo.hpAtual/alvo.status.hpMax<.5?dano*1.15:dano;} },
  H107: { aoDerrotarInimigo(proprio){proprio.hpAtual=Math.min(proprio.status.hpMax,proprio.hpAtual+Math.max(1,Math.floor(proprio.status.hpMax*.08)));} },
  H108: { antesDoTurno(proprio){if(proprio.hpAtual/proprio.status.hpMax<.3&&!proprio._reserva){proprio.status.ataqueEspecial=Math.floor(proprio.status.ataqueEspecial*1.15);proprio._reserva=true;}} },
  H109: { modificarDano(proprio,alvo,dano){return proprio.hpAtual>=proprio.status.hpMax?dano*1.1:dano;} },
  H110: { aoSerAtingido(proprio,atacante,golpe,batalha){if(Math.random()<.1&&atacante&&golpe?.poder>0){const d=Math.max(1,Math.floor((proprio._ultimoDanoRecebido||0)*.25));atacante.hpAtual=Math.max(0,atacante.hpAtual-d);batalha.log.push(`${proprio.nome} refletiu ${d} de dano!`);}} },
  H111: { aoEntrar(proprio){const s=['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade'][Math.floor(Math.random()*5)];proprio.status[s]=Math.floor(proprio.status[s]*1.1);} },
  H112: { aoEntrar(proprio,oponente,batalha){if(batalha._trocaEquivalenteFeita||!oponente?.status)return;const stats=['ataque','defesa','ataqueEspecial','defesaEspecial','velocidade'];const maior=m=>Math.max(...stats.map(s=>Number(m.status[s]||0)));const meus=maior(proprio),dele=maior(oponente);const meusStats=stats.filter(s=>Number(proprio.status[s]||0)===meus);const deleStats=stats.filter(s=>Number(oponente.status[s]||0)===dele);meusStats.forEach(s=>proprio.status[s]=dele);deleStats.forEach(s=>oponente.status[s]=meus);batalha._trocaEquivalenteFeita=true;batalha.log.push(`Troca Equivalente! ${proprio.nome} trocou seu(s) maior(es) atributo(s) com ${oponente.nome}.`); } },
};

function habilidadeDe(monstro){ return monstro && monstro.habilidade ? HABILIDADES[monstro.habilidade]||null : null; }
function nomeHabilidade(codigo){ return HABILIDADE_NOMES[codigo]||codigo||''; }
function codigoHabilidade(nome){ return HABILIDADE_CODIGOS[nome]||nome||''; }
function estaImune(monstro,status){const h=habilidadeDe(monstro);return !!(h&&h.imunidades&&h.imunidades.includes(status));}
function nomeStatus(s){return ({hpMax:'HP',ataque:'Ataque',defesa:'Defesa',ataqueEspecial:'Ataque Especial',defesaEspecial:'Defesa Especial',velocidade:'Velocidade'})[s]||s;}

// Helpers usados pela Brecha/Contra ataque sem depender da ordem dos scripts.
function buscarGolpeGlobal(codigo){ return (typeof DADOS_GOLPES!=='undefined' ? DADOS_GOLPES.find(g=>g.codigo===codigo) : null); }
function calcularEfetividadeGlobal(g,a,t){ return (typeof calcularEfetividade==='function' ? calcularEfetividade(g.tipo,t.tipo) : 1); }
function calcularDanoGlobal(a,t,g,ef,b){ if(!g||g.poder<=0||ef===0)return 0; let atk=g.categoria==='Físico'?a.status.ataque:a.status.ataqueEspecial; let def=g.categoria==='Físico'?t.status.defesa:t.status.defesaEspecial; let base=(((2*a.nivel/5+2)*g.poder*(atk/def))/50+2); if(a.tipo.split('/').map(x=>x.trim()).includes(g.tipo))base*=1.5; if(a.statusAlterado==='queimado'&&g.categoria==='Físico')base*=.5; if(b.campoNoturno&&g.tipo==='Dark')base*=1.5; return Math.max(1,Math.floor(base*ef*(.85+Math.random()*.15))); }

const EFEITOS_DE_CAMPO_POR_NOME={Shalung:b=>{b.estrelado=true;},Sabic:b=>{b.florido=true;}};
